name: Just Another Admin
markdown: kramdown
theme: jekyll-theme-cayman
permalink: /blog/:year/:month/:day/:title
url: "https://soccershoe.github.io/JustAnotherAdmin" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate



#paginate: 5

#paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
#paginate_path: "/blog/page:num/"