name: Just Another Admin
markdown: kramdown
theme: jekyll-theme-cayman
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate

paginate: 5
paginate_path: "/JustAnotherAdmin/blog/page:num/"