name: Just Another Admin
markdown: kramdown
theme: slate
permalink: /blog/:year/:month/:day/:title
url: "https://soccershoe.github.io/JustAnotherAdmin" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions

#paginate:5



#paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
#paginate_path: "/blog/page:num/"

#these plugins seem to work 9/19/19
# - jekyll-feed
# - jemoji
# - jekyll-mentions