name: Just Another Admin
description:  This is my site for sharing back with the IT world.
markdown: kramdown
#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
permalink: /blog/:year/:month/:day/:title
paginate_path: /blog/page:num/
baseurl: "/JustAnotherAdmin" # the subpath of your site, e.g. /blog
url: "https://soccershoe.github.io" # the base hostname & protocol for your site
excerpt_separator: "{{ more }}"
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
  - jekyll-remote-theme
#  - jekyll-seo-tag  ## this is for enabling in the just-the-docs theme. not sure if this plugin is whitelisted by default for Github Pages
  

### all stuff for the 'just-the-docs' theming ###
#logo: "/assets/GokuLogoT.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Just Another Admin":
    - "//github.com/soccershoe"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; This Guy. Distributed by <a href=\"https://github.com/soccershoe/\">MY license.</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10

### end just-the-docs configurations ###



#paginate:5



#paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
#paginate_path: "/blog/page:num/"


#these plugins seem to work 9/19/19
# - jekyll-feed
# - jemoji
# - jekyll-mentions
