name: Just Another Admin
markdown: kramdown
theme: pmarsceill/just-the-docs
permalink: /blog/:year/:month/:day/:title
paginate_path: /blog/page:num/
baseurl: "/JustAnotherAdmin" # the subpath of your site, e.g. /blog
url: "https://soccershoe.github.io" # the base hostname & protocol for your site
excerpt_separator: "{{ more }}"
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
  - jekyll-remote-theme
  








#paginate:5



#paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
#paginate_path: "/blog/page:num/"

#these plugins seem to work 9/19/19
# - jekyll-feed
# - jemoji
# - jekyll-mentions